### ISSUE TITLE
PostgreSQL version decision needed

### ISSUE THREAD

**Issue by znmeb** [hackoregon/hack-university-data-architecture#14]
PostgreSQL 9.6.1 is now the latest stable version (https://www.postgresql.org/). However, the default in Ubuntu 16.04 LTS "Xenial Xerus" is 9.5. I haven't looked at the differences yet. In any event between Data Architecture and the Database class we need to choose one or the other.

Personally I'd choose 9.6 and modify our install scripts to get that version. But I can live with 9.5 if that's what people want.

**Comment by znmeb** [comment]
Here's a little more research on the PostgreSQL 9.5 vs. 9.6:

Feature matrix: https://www.postgresql.org/about/featurematrix/
The bottom line is for large problems 9.6 has better performance and 9.6 has a few more analytical features inside the database engine. I'd be surprised if anything we do will show a significant improvement.

Other tradeoffs:
1. The default with Ubuntu 16.04LTS is 9.5.
2. We used 9.5 for Crop Compass ... any people who worked on that project that are back this season are familiar with 9.5. That's at least Heidi Perry, Michael Moorman and myself. I don't know what the other teams used.
3. PgAdmin: 9.6 uses a new version of the GUI administration tool, PgAdmin 4. This is a complete rewrite from the ground up and isn't packaged for Ubuntu yet. We used PgAdmin 3 on Crop Compass.

I've got PgAdmin 4 / PostgreSQL 9.6 / PostGIS 2.3 set up on my workstation and on my laptop and will be getting up to speed on them so if we do go that route I'll be ready.

I've got two open issues on the laptop scripts for this pending the decision. It's about half a day to implement if we go with 9.6; no work at all if we go with 9.5.

**Comment by sanjuroj** [comment]
In the interest of simply making an initial decision, can we go with 9.5?  I don't think it's a terrible idea to be one point release behind, and since it seems all around easier to stick with 9.5, how about we just do that?  We can always consider moving to (or creating a special vagrant box for etc...) 9.6 if we find a compelling reason.

**Comment by znmeb** [comment]
yep ... we're going with 9.5 and PostGIS 2.2. Closing the issue.
